### ISSUE TITLE
Debounce vs update interval?

### ISSUE THREAD

**Issue by bludin** [adafruit/Adafruit_CircuitPython_Debouncer#32]
I have problems understanding how the debouncer works. debouncer_timing_test.py calls update() with a 100ms interval. The (default) debounce interval is only 10ms,though. How does the debouncer catch and handle, lets say, a 50ms dip that happens between updates? Thanks, Beat

**Comment by dastels** [comment]
The interval is the length of time that the input that's being debounced has to be in a new state (sampled on each call to **update()** ) before it's considered to have changed. So if you have a switch that takes less than 10mS to settle, a 10mS interval is good. If the switch is slower to settle, you would need a longer interval.

The **update()** method needs to be called several times during an interval amount of time. As often as possible, really, regardless of what the interval is.

Now for your example of a 50mS pulse. With a 100mS interval, it doesn't matter how often you call **update()**, the pulse will be filtered out since the signal goes low and high again after 50mS... it doesn't stay low for >= 100mS so it is considered noise. With a 10mS interval, the edges would get recognized, assuming you call **update()** frequently enough.

Note that the debouncer relies on **update()** being called frequently, say... every 1mS or so, more often is better. That means that your main loop has to be tight and fast, with no calls to **sleep()** to slow it down. See [this guide](https://learn.adafruit.com/multi-tasking-with-circuitpython) for an overview of how to program without using **sleep()** for timing (and also write pseudo-concurrent code). Also, read the [debouncer tutorial](https://learn.adafruit.com/debouncer-library-python-circuitpython-buttons-sensors) if you haven't yet.

**Comment by bludin** [comment]
Thanks for the detailed explanation. I did get it right. It was just confused by the use of `time.sleep(0.1)` in your [example](https://github.com/adafruit/Adafruit_CircuitPython_Debouncer/blob/main/examples/debouncer_timing_test.py) then.
Anyway, calling update that often might often be impossible. Do you think it might be possible to use pulseio.PulseIn for retrospective debouncing?

**Comment by dastels** [comment]
No idea. You wouldn't do that in real code.

**Comment by FoamyGuy** [comment]
Closing this for now. If I understand correctly this was asking for clarification about the library and turned out not to represent an issue with the code. 

If I have misunderstood this can be re-opened if needed.
